channels:
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - tensorflow
  - matplotlib
  - nltk
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - opencv
  - pillow
  - keras-tuner
  - pydot
  